# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebAppName: 'HelloWorldIIS'
  IISWebSiteName: 'Default Hello World Web Site'

resources:
 pipelines:
   - pipeline: 'BuildPipeline'
     project: 'ProjectOne'
     source: 'basic-dotnet-projects'
     branch: 'main'

stages:
  - stage: Stage_DeployWebApp
    displayName: 'Stage - Deploy WebApp'
    
    jobs:
      - deployment: Job_DeployWebApp
        displayName: 'Job - Deploy WebApp'
        environment: 'IIS-Dev'
        strategy:
         runOnce:
           deploy:
             steps:
               - checkout: self
               
               - script: | 
                  echo "Hello World!"
              