stages:
  - stage: Build
    displayName: Build Application
    jobs:
    - job: Build
      pool:
        name: SelfHostedAgents        
      steps:           
      - template: templates-steps.yml